hostname: rancher.local
replicas: 1
bootstrapPassword: "admin"

ingress:
  enabled: true
  tls:
    source: secret
  extraAnnotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

privateCA: false

resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 30

auditLog:
  level: 1

busyboxImage: busybox:1.36.1